# Generated by Django 5.2.6 on 2025-11-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guia')),
                ('producto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('dimensiones', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Dimensiones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
    ]
