# Generated by Django 5.2.6 on 2025-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_model',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de regsitro'),
        ),
    ]
