# Generated by Django 5.2.6 on 2025-11-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_catalogo_model_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_model',
            name='imagen',
        ),
    ]
