# Generated by Django 5.2.6 on 2025-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_catalogo_model_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
