# Generated by Django 5.2.6 on 2025-11-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_catalogo_model_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_model',
            name='guia',
        ),
    ]
